### ISSUE TITLE
Oddity with bin/natalie in interactive use - repeats input, also is slow

### ISSUE THREAD

**Issue by rubyFeedback** [natalie-lang/natalie#1086]
Hey,

I just compiled natalie from the current git source. It compiled fine.

I then started bin/natalie.

Now here is something strange - first the image https://i.imgur.com/TunxuWO.png

I was typing:

    class Joe

But oddly enough, interactive natalie keeps on repeating that input. No idea why.
Is it trying to use .irbrc or something? I don't know why the inputted words get
repeated.

There is also another oddity in that when I do e. g:

    5+5

in bin/natalie, interactive, it takes perhaps 3 seconds or so before it finishes
evaluation. No clue why.

Anyway just reporting this to make sure this issue is known. Keep up the work
on natalie!

**Comment by seven1m** [comment]
Yes, this is known. We rebuilt the REPL to be a bit more flexible, but there are bugs. Also, since Natalie is an AOT compiled language, every time you type something in the REPL, it has to compile the code and run it, which takes a bit of time.

Since the bug report here is "make the REPL better" I'm going to close this for now. If you want to lend a hand working on making it better, please dive right in! 🤗
