### ISSUE TITLE
REPL repeats input sometimes

### ISSUE THREAD

**Issue by rubyFeedback** [natalie-lang/natalie#1160]
Hey there Tim,

Every now and then I test natalie to see how usable it has become. :)

In the interactive nat,  aka bin/natalie, we can type in ruby code and it
is evaluated. The evaluation is a bit slow, so if you may have time in
the future, perhaps the parser/lexer or whatever else is evaluating the
code, could become faster. But this is an aside; the main gist here is
the odd repetitive behaviour I see.

First, here is the image, a partial screenshot of two separate natalie
sessions ("irb" sessions):

https://i.imgur.com/66IIVDB.png

In particular in the middle of the image, I was typing "def foobar", 
and oddly enough, tons of extra "def foobar" lines appeared, but
I only typed it once. I believe something in the interactive natalie
repeats this, probably to help with spacing and indent (or this is
what I think may be going on). The awkward thing is that sometimes
it does NOT repeat it, and sometimes it repeats it like those 8
times. 

I am not sure how to easily reproduce the bug, but I believe that
in whatever routine is used to determine repetition, something
may be wrong since it seems to repeat it when it really should
not (or, at the least, not repeat it more than once, not sure why
it is ever repeated more than once ... I could perhaps wrap my
head around repeating it once, if you want to show things with
some indent, but it is like repeated 5 times sometimes, and I
don't understand why or the rationale behind this, so I believe
this is most likely a small bug). Anyway, just reporting this in
the event it comes to your attention in the future if you 
re-visit the irb-like part of natalie again. Onwards to 100%
compatbiility! \o/

**Comment by rubyFeedback** [comment]
Oh yes, what may not be instantly obvious - at first the "foobar"
is white, which I think comes from when I type it, but the
subsequent repetitions are yellow in colour, so probably some
re-parsing and redrawing or something occurred, because the
colour changed. And also perhaps a way can be added to disable
this, in the event it causes oddities.

**Comment by seven1m** [comment]
>The evaluation is a bit slow, so if you may have time in
the future, perhaps the parser/lexer or whatever else is evaluating the
code, could become faster.

Yes, this is expected. Natalie will not (in the near future at least) be very fast at evaluating a single line of code in the interactive REPL, because Natalie is an AOT compiler. Natalie must compile each line to machine code in order to execute it. So that probably won't get a lot better until we implement the rest of our VM, which is not the top of my priorities right now.

>In particular in the middle of the image, I was typing "def foobar",
and oddly enough, tons of extra "def foobar" lines appeared, but
I only typed it once. 

Thank you for the bug report. Our REPL was rewritten to support autocomplete and some other interactive features, but I have noticed there are some bugs with the repetition, as you have mentioned. We can leave this issue open as a tracker for the buggy REPL.

Thanks.
