### ISSUE TITLE
Sandboxing?

### ISSUE THREAD

**Issue by Nakilon** [natalie-lang/natalie#564]
Rather a question than an issue.
I wonder if it's possible to use this Ruby implementation for a sandboxing purposes. For example, earlier Ruby had the global variable `$SAFE` that could disable things like writing to network sockets. It would be cool to have some flags that when natalie compiles the Ruby code they make sure that the socket-writing or file-writing libraries were not included during the compilation. Not sure how much it's possible but for different purposes, such as chat REPL or maybe an educational online code executor I wanted a way to be sure I can run someone's Ruby code without a risk of it doing something inappropriate.

**Comment by seven1m** [comment]
Yeah that sounds totally doable. I like the idea. Right now, it would just be file IO, but I hope to get socket support added soon.

Thanks for the idea!

(Closing this for now since it isn't really a bug, but I will keep it in mind going forward. If you have an idea for implementation, feel free to throw up a PR!)
