### ISSUE TITLE
Why not use MRI's stdlib?

### ISSUE THREAD

**Issue by camertron** [natalie-lang/natalie#566]
Hey everyone! 👋  This is a really interesting project. I've always wanted to be able to compile Ruby :)

I've been reading through the docs and issues and found myself wondering why you're rewriting the entire Ruby standard library from scratch. Surely it should be possible to reuse MRI's stdlib?

**Comment by seven1m** [comment]
For fun!

Actually, we may not do that for all the libraries, but for any that use C code, it’s necessary right now since we do not have a C API that’s compatible with MRI. (But that’s something we may add later!)

If you see a particular stdlib thing you want to help get working, please let us know! ❤️
